### ISSUE TITLE
运行遇到一个报错，可以帮忙看一下吗，谢谢

### ISSUE THREAD

**Issue by yydcyy01** [C0nw0nk/ExtractNow#1]
>“ 'go' 不是内部或外部命令，也不是可运行的程序或批处理文件。”

>start /wait /B %root_path%%root_file_name_and_extension% go  
55行代码有这个go语句。不太理解什么意思。请指教

**Comment by C0nw0nk** [comment]
Fixed it for you.

Its just so that the script will loop and rescan the directory running the extract program so for example when the script ends or runs `exit` it will go back to the start. Its my trick for looping the batch file until you close the window.

Anyway appending a nul value to the end of it makes it so you no longer see the message
